# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cd84132f56df74280fb6dc0773b43d2c6eb2e221aabb0fcd3bb8c027325a5fee5a71fb35cf9c1ca926fef4c2bf6c6f8430e3efd9a8b03f276b4fac946838a1b

test:
  secret_key_base: 2e6d0988bae0d3ff93f5109eb2c8247b7d57e0f2966c6328c15490b4c34ea67b5d85f460de1bab431999a91e317965b828813fe5c1ff58c9d745aab46a248ffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
